<a href="https://colab.research.google.com/github/JasmanjotSarna/AI-ML-Learning/blob/main/Pandas/Pandas_Core_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Series**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels= ['a','b','c']
lists=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [ ]:
pd.Series(lists)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(lists,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

## **DataFrames**

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
column=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=column)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and Indexing of Columns

In [ ]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a New Column

In [ ]:
df2["Designation"] = ["Engineer","Manager","HR","CA"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000          HR
3  Linda   42    London   85000          CA

### Removing Columns

In [ ]:
df2.drop('Designation', axis=1,inplace= True)

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop(['City','Salary'], axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

### Selecting Rows

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

In [ ]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [ ]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

### Conditional Selections

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

### Missing Data

## **Finding Missing Data**

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

## **Removing Missing Data**

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## **Filling the Missing Data**

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values={'A':50,'B':100,'C':300,'D':400}
df.fillna(value=values)

      A  B      C      D
0   1.0  1    1.0    1.0
1   2.0  2    2.0  400.0
2  50.0  3    3.0  400.0
3   4.0  4  300.0  400.0
4   5.0  5  300.0    5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(df.mean)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,<bound method DataFrame.mean of A B C...
2,<bound method DataFrame.mean of A B C...,3,3.0,<bound method DataFrame.mean of A B C...
3,4.0,4,<bound method DataFrame.mean of A B C...,<bound method DataFrame.mean of A B C...
4,5.0,5,<bound method DataFrame.mean of A B C...,5.0

## **Merging 2 DataFrames**

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
 pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
 pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
 pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
 pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

## **Concatination of 2 DataFrames**

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## **Joining of 2 DataFrames**

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [ ]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

## **GroupBy**

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df1=df.groupby('Category')
for i,v in df1:
  print(i)
  print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [ ]:
df1=df.groupby('Category')['Sales'].sum()
df1

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
df1=df.groupby(['Category','Store'])['Sales'].sum()
df1

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## **Aggregation**

In [ ]:
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].median()

190.0

In [ ]:
df['Sales'].min()

100

In [ ]:
df['Sales'].max()

300

In [ ]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].std()

66.06274074155351

In [ ]:
df['Sales'].agg(['mean','median','min','max','std'])

mean      187.500000
median    190.000000
min       100.000000
max       300.000000
std        66.062741
Name: Sales, dtype: float64

## **Pivot Tables**

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [ ]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    803     23   John  January      Q1
1  2023-01-02       B   West    875     49   Mary  January      Q1
2  2023-01-03       C  North    426     45    Bob  January      Q1
3  2023-01-04       D  South    248     72  Alice  January      Q1
4  2023-01-05       A   East    644     81   John  January      Q1
5  2023-01-06       B   West    967     22   Mary  January      Q1
6  2023-01-07       C  North    337     27    Bob  January      Q1
7  2023-01-08       D  South    199     66  Alice  January      Q1
8  2023-01-09       A   East    496     70   John  January      Q1
9  2023-01-10       B   West    567     78   Mary  January      Q1
10 2023-01-11       C  North    691     34    Bob  January      Q1
11 2023-01-12       D  South    923     93  Alice  January      Q1
12 2023-01-13       A   East    503     29   John  January      Q1
13 2023-01-14       B   West    302     98   Mary  January      Q1
14 2023-01-15       C  North    620     64    Bob  January      Q1
15 2023-01-16       D  South    553     32  Alice  January      Q1
16 2023-01-17       A   East    424     57   John  January      Q1
17 2023-01-18       B   West    454     66   Mary  January      Q1
18 2023-01-19       C  North    881     98    Bob  January      Q1
19 2023-01-20       D  South    854     57  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     503.0    NaN    NaN    NaN
North      NaN    NaN  620.0    NaN
South      NaN    NaN    NaN  553.0
West       NaN  567.0    NaN    NaN

In [ ]:
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     574.0    NaN    NaN    NaN  52.0   NaN   NaN   NaN
North      NaN    NaN  591.0    NaN   NaN   NaN  53.6   NaN
South      NaN    NaN    NaN  555.4   NaN   NaN   NaN  64.0
West       NaN  633.0    NaN    NaN   NaN  62.6   NaN   NaN

## **Cross Tabs**

In [ ]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    803     23   John  January      Q1
1  2023-01-02       B   West    875     49   Mary  January      Q1
2  2023-01-03       C  North    426     45    Bob  January      Q1
3  2023-01-04       D  South    248     72  Alice  January      Q1
4  2023-01-05       A   East    644     81   John  January      Q1
5  2023-01-06       B   West    967     22   Mary  January      Q1
6  2023-01-07       C  North    337     27    Bob  January      Q1
7  2023-01-08       D  South    199     66  Alice  January      Q1
8  2023-01-09       A   East    496     70   John  January      Q1
9  2023-01-10       B   West    567     78   Mary  January      Q1
10 2023-01-11       C  North    691     34    Bob  January      Q1
11 2023-01-12       D  South    923     93  Alice  January      Q1
12 2023-01-13       A   East    503     29   John  January      Q1
13 2023-01-14       B   West    302     98   Mary  January      Q1
14 2023-01-15       C  North    620     64    Bob  January      Q1
15 2023-01-16       D  South    553     32  Alice  January      Q1
16 2023-01-17       A   East    424     57   John  January      Q1
17 2023-01-18       B   West    454     66   Mary  January      Q1
18 2023-01-19       C  North    881     98    Bob  January      Q1
19 2023-01-20       D  South    854     57  Alice  January      Q1

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## **Operations**

### Basic Operation

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

### **DataFrame Applying Functions**

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
  return x**2

In [ ]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df1['D']=df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [ ]:
df1['B'].apply(lambda x: x**2)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64